# -*- coding: utf-8 -*-
"""Fasta_File_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I03g4yBO3Jzz7slCjHKeaODth4Jyebbi
"""

pip install biopython

filename="/content/sequence.fasta"

from Bio import SeqIO

records = list(SeqIO.parse(filename, "fasta"))

if records:
    print(f"Number of records found: {len(records)}")
    print("\nFirst record details:")
    first_record = records[0]
    print(f"ID: {first_record.id}")
    print(f"Description: {first_record.description}")
    print(f"Sequence length: {len(first_record.seq)}")
    print(f"Sequence: {str(first_record.seq)[:75]}")
else:
    print("No records found in the FASTA file.")

if records:
    nucleotide_counts = {"A": 0, "T": 0, "C": 0, "G": 0}
    sequence_str = str(first_record.seq).upper()

    for nucleotide in sequence_str:
        if nucleotide in nucleotide_counts:
            nucleotide_counts[nucleotide] += 1

    print("\nNucleotide counts:")
    for nuc, count in nucleotide_counts.items():
        print(f"{nuc}: {count}")
else:
    print("No records found to count nucleotides")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

if 'nucleotide_counts' in locals() and nucleotide_counts:
    # Convert the dictionary to a pandas DataFrame for easier plotting
    df_nucleotide_counts = pd.DataFrame(nucleotide_counts.items(), columns=['Nucleotide', 'Count'])

    fig = plt.figure(figsize=(8, 6))
    sns.barplot(x='Nucleotide', y='Count', data=df_nucleotide_counts, palette='viridis')
    plt.title('Nucleotide Distribution')
    plt.xlabel('Nucleotide')
    plt.ylabel('Count')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()
else:
    print("Nucleotide counts not available or empty")

if 'df_nucleotide_counts' in locals():
    csv_filename = 'nucleotide_counts.csv'
    df_nucleotide_counts.to_csv(csv_filename, index=False)
    print(f"Nucleotide counts saved to {csv_filename}")
else:
    print("DataFrame 'df_nucleotide_counts' not found. Please ensure nucleotide counts have been generated.")

if 'nucleotide_counts' in locals() and nucleotide_counts:
    g_count = nucleotide_counts.get('G', 0)
    c_count = nucleotide_counts.get('C', 0)
    a_count = nucleotide_counts.get('A', 0)
    t_count = nucleotide_counts.get('T', 0)

    total_nucleotides = g_count + c_count + a_count + t_count

    if total_nucleotides > 0:
        gc_content = ((g_count + c_count) / total_nucleotides) * 100
        print(f"GC-content: {gc_content:.2f}%")
    else:
        print("Cannot calculate GC-content")
else:
    print("Nucleotide counts not available")