# -*- coding: utf-8 -*-
"""GC_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v5bsE3miarqEe3ecCpEUgRt9zTCLpk_O
"""

pip install biopython

filename="/content/sequence.fasta"

from Bio import SeqIO

records = list(SeqIO.parse(filename, "fasta"))

if records:
    print(f"Number of records found: {len(records)}")
    print("\nFirst record details:")
    first_record = records[0]
    print(f"ID: {first_record.id}")
    print(f"Description: {first_record.description}")
    print(f"Sequence length: {len(first_record.seq)}")
    print(f"Sequence: {str(first_record.seq)[:75]}")
else:
    print("No records found in the FASTA file.")

if 'nucleotide_counts' in locals() and nucleotide_counts:
    g_count = nucleotide_counts.get('G', 0)
    c_count = nucleotide_counts.get('C', 0)
    a_count = nucleotide_counts.get('A', 0)
    t_count = nucleotide_counts.get('T', 0)

    total_nucleotides = g_count + c_count + a_count + t_count

    if total_nucleotides > 0:
        gc_content = ((g_count + c_count) / total_nucleotides) * 100
        print(f"GC-content: {gc_content:.2f}%")
    else:
        print("Cannot calculate GC-content")
else:
    print("Nucleotide counts not available")