# -*- coding: utf-8 -*-
"""Gene_bank_parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-Gui3DFTAsA7clImXTjFsUkaGT3KFBI
"""

from Bio import SeqIO

pip install biopython

file_path="/content/sequence.gb"

gb_obj= SeqIO.read(file_path,"genbank")

genes=[]

genes = []
for feature in gb_obj.features:

    if feature.type == "gene":
        genes.append(feature) # Append the entire feature object

if gb_obj.features:
    first_feature = gb_obj.features[0]
    print("Type of first feature:", type(first_feature))
    print("Attributes of first feature:")
    for attr in dir(first_feature):
        if not attr.startswith('__'):
            try:
                value = getattr(first_feature, attr)
                # Avoid printing very long sequence objects or complex internal objects directly
                if not callable(value) and not isinstance(value, (list, dict)) and len(str(value)) < 200:
                    print(f"  {attr}: {value}")
                elif isinstance(value, (list, dict)) and len(value) < 5:
                    print(f"  {attr}: {value}")
                elif attr == 'location':
                    print(f"  {attr}: {value}")
                elif attr == 'qualifiers':
                    print(f"  {attr}: {value}")
            except Exception as e:
                print(f"  {attr}: <error accessing attribute: {e}> ")
else:
    print("No features found in gb_obj.")

genes = []
len(genes)

gene_of_interest="rpoB"

hit=[]

hit = [] # Initialize hit list
for gene_feature in genes:
  # Check if 'gene' qualifier exists and if gene_of_interest is in its list of values
  if 'gene' in gene_feature.qualifiers and gene_of_interest in gene_feature.qualifiers['gene']:
   hit.append(gene_feature)
   print(f'Gene found: {gene_of_interest}')

if hit:
    first_hit_feature = hit[0]
    print("Type of first hit feature:", type(first_hit_feature))
    print("Attributes of first hit feature:")
    for attr in dir(first_hit_feature):
        if not attr.startswith('__'):
            try:
                value = getattr(first_hit_feature, attr)
                if not callable(value) and not isinstance(value, (list, dict)) and len(str(value)) < 200:
                    print(f"  {attr}: {value}")
                elif isinstance(value, (list, dict)) and len(value) < 5:
                    print(f"  {attr}: {value}")
                elif attr == 'location':
                    print(f"  {attr}: {value}")
                elif attr == 'qualifiers':
                    print(f"  {attr}: {value}")
            except Exception as e:
                print(f"  {attr}: <error accessing attribute: {e}> ")
else:
    print("No genes found in the 'hit' list.")

if not genes:
    print("The 'genes' list is empty. Let's inspect the feature types in gb_obj.features to understand why.")
    unique_feature_types = set()
    for feature in gb_obj.features:
        unique_feature_types.add(feature.type)
    print(f"Unique feature types in gb_obj.features: {list(unique_feature_types)}")
else:
    print("Genes list is not empty, inspecting the first element:")
    first_gene_in_genes = genes[0]
    print("Type of first gene in genes:", type(first_gene_in_genes))
    print("Attributes of first gene in genes:")
    for attr in dir(first_gene_in_genes):
        if not attr.startswith('__'):
            try:
                value = getattr(first_gene_in_genes, attr)
                if not callable(value) and not isinstance(value, (list, dict)) and len(str(value)) < 200:
                    print(f"  {attr}: {value}")
                elif isinstance(value, (list, dict)) and len(value) < 5:
                    print(f"  {attr}: {value}")
                elif attr == 'location':
                    print(f"  {attr}: {value}")
                elif attr == 'qualifiers':
                    print(f"  {attr}: {value}")
            except Exception as e:
                print(f"  {attr}: <error accessing attribute: {e}> ")


print("Inspecting all features in gb_obj:")
for i, feature in enumerate(gb_obj.features):
    print(f"Feature {i+1} ")
    print(f"Type: {feature.type}")
    print(f"Location: {feature.location}")
    if feature.qualifiers:
        print("Qualifiers:")
        for key, value in feature.qualifiers.items():
            print(f"  {key}: {value}")
    else:
        print("No qualifiers found for this feature.")

feature_type_counts = {}
for feature in gb_obj.features:
    feature_type = feature.type
    feature_type_counts[feature_type] = feature_type_counts.get(feature_type, 0) + 1

print("Feature type counts:")
for f_type, count in feature_type_counts.items():
    print(f"  {f_type}: {count}")

unique_qualifier_keys = set()
for feature in gb_obj.features:
    for key in feature.qualifiers.keys():
        unique_qualifier_keys.add(key)

print("Unique qualifier keys across all features:")
for key in sorted(list(unique_qualifier_keys)):
    print(f"- {key}")
